name: Beyond Physical
favicon: null
layout_spectrum: 0.88072
typography_spectrum: 0.97355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#717845'
    - '#464e29'
    - '#d2c2b3'
    - '#f2f7fd'
    - '#0e0a09'
  brandStrength: 0.75
  lightness: 0.6303008822724223
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
